language: go
sudo: false
go:
  - 1.20.x
  - 1.21.x
  - 1.22.x
cache:
  directories:
    - vendor
install:
  - npm i uber-licence
  - make dependencies
script:
  - make test
  - make lint
after_success:
  - make coveralls
